server:
  port: 8080

spring:
  thymeleaf:
    enabled: true
    prefix: classpath:templates/
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect

# 전체 로그 레벨 설정(기본 info)
logging.level.root: info

---

spring:
  profiles:
    active: prod

---

spring:
  profiles:
    active: local

