server:
  port: 8080

spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: file:src/main/resources/templates/
  freemarker:
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/example?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull&allowPublicKeyRetrieval=true
    username: testuser
    password: 5678
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop
      #      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDB53Dialect

# 전체 로그 레벨 설정(기본 info)
logging.level.root: info

# hello.springmvc 패키지와 그 하위 로그 레벨 설정
logging.level.sbs.apidemo: debug
